name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4.2.2

      - name: Set up python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.13'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pip dependencies
        run: pip install build gradio

      - name: Install npm dependencies
        working-directory: sync3dcompare/frontend
        run: npm install

      - name: Build frontend
        working-directory: sync3dcompare
        run: gradio cc build --python-path $(which python)

      - name: List pip dependencies
        run: pip list

      - name: Build project
        working-directory: sync3dcompare
        run: python3 -m build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: pypi-dist
          path: sync3dcompare/dist/

  pypi:
    name: pypi
    needs:
      - build
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5.0.0
        with:
          name: pypi-dist
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
